# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a0f93a49fdff3fb1cb3ef276dca8404b627bc5326d596d7461357bd7d53cd7f77ea2d5169893008047361d134a1a1a51515df3113719616398e703518f18072

test:
  secret_key_base: f44bfbf00deac2a1602a71a725158d287460362bfc3e5afe7b2c0f772b1430164ef8200d74d5bd10ade522c3289abd8819abea5714fcaff1d4469283a308b869

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
